basePath: /api
definitions:
  email.MailMessage:
    properties:
      body:
        example: <h1>Hello, world!</h1>
        type: string
      cc:
        example:
        - test@test.com
        - ' test2@test2.com'
        items:
          type: string
        type: array
      from:
        example: marceloamoreno87@gmail.com
        type: string
      subject:
        example: testing
        type: string
      to:
        example:
        - test@test.com
        - ' test2@test2.com'
        items:
          type: string
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: marceloamoreno87@gmail.com
    name: Marcelo Moreno
  description: Serviço de API para enviar email.
  title: GOMAIL
  version: "1.0"
paths:
  /send-email:
    post:
      description: Send email by HTML template
      parameters:
      - description: query params
        in: body
        name: doc
        required: true
        schema:
          $ref: '#/definitions/email.MailMessage'
      produces:
      - application/json
      responses: {}
      summary: Send email by HTML template
      tags:
      - Send email
swagger: "2.0"
